### ISSUE TITLE
Does not work out of box

### ISSUE THREAD

**Issue by InsightlyYours** [procore/js-sdk-sample-app#5]
This no longer works out of the box.  I have tried on Ubuntu, MacOS, and Windows10.  There are a number of issues:
-The .json file contains three lines (<<<<<<< HEAD, =======, and >>>>>>> fix: set up credentials correctly) which prevent yarn from running.
-If those lines are removed and @procore/js-sdk imported correctly, npm run rollup:build doesn't work because: 'default' is not exported by 'node_modules\core-js\library\modules\es6.object.to-string.js'
and 'default' is not exported by 'node_modules\whatwg-fetch\fetch.js'

The full errors for those last two are:

'default' is not exported by 'node_modules\core-js\library\modules\es6.object.to-string.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
 commonjs-proxy: <path>\node_modules\core-js\library\modules\es6.object.to-string.js (1:321)
1: import * as es6_object_toString from <path>\node_modules\core-js\library\modules\es6.object.to-string.js; export default ( es6_object_toString && es6_object_toString['default'] ) || es6_object_toString;

'default' is not exported by 'node_modules\whatwg-fetch\fetch.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
 commonjs-proxy:<path>\node_modules\whatwg-fetch\fetch.js (1:251)
1: import * as fetch from <path>\node_modules\whatwg-fetch\fetch.js"; export default ( fetch && fetch['default'] ) || fetch;

I suspect this may be due to the update to es6, which changed how exports were handled (you have to explicitly default them.

**Comment by InsightlyYours** [comment]
Partially fixed by forcing rollup to an older version.  "rollup": "<0.40.0" in the packages.json does not cause any export errors.

**Comment by ksespinola** [comment]
Resolved.
https://github.com/procore/js-sdk-sample-app/pull/7
