### ISSUE TITLE
yarn install not working

### ISSUE THREAD

**Issue by H-Indiana-Holdsworth** [procore/js-sdk-sample-app#50]
Hi! I'm trying to do the `yarn install cp packages/server/.env.example packages/server/.env` command and I'm getting this error: "error `install` has been replaced with `add` to add new dependencies. Run "yarn add cp packages/server/.env.example packages/server/.env" instead."

 So, I run the suggested command and then I get this: "error An unexpected error occurred: "https://registry.yarnpkg.com/packages%2fserver/.env.example: Request \"https://registry.yarnpkg.com/packages%2fserver/.env.example\" returned a 405"."

I've created a lot of my own projects but am new to open source, so this could totally be a simple issue on my end, would love some help, thanks!

**Comment by astanley86** [comment]
It looks like you have combined the `yarn install` command with the `cp packages/server/.env.example packages/server/.env` command.  Try running only `yarn install` and wait for that to finish.  Then run the `cp packages/server/.env.example packages/server/.env` next.

**Comment by gilmcquillan** [comment]
@astanley86 is correct. These commands must be run separately from the root of the repo.
